### ISSUE TITLE
Quantity error on Add to cart

### ISSUE THREAD

**Issue by petrovnn** [karthikeyan-manivasagam/basic_cart#1]
If quantity option is disabled, anonym get JS error on Add to cart button (ajax request):
/cart/add/3?entitytype=node&quantity=undefined 403 (Forbidden)

under admin - it's okay, no error, URL same, but no error:
/cart/add/3?entitytype=node&quantity=undefined  200 (ok)

you can see it here in action:
http://techmobile.ru 

how can i fix it?

**Comment by karthikeyan-manivasagam** [comment]
![permissions site](https://cloud.githubusercontent.com/assets/19973271/22816064/a8b2d6e8-ef85-11e6-9a82-05cbd5d10915.png)
Hi  @petrovnn  ,  Please make sure that you have enabled the permission to use basic cart for anonymous user.

**Comment by petrovnn** [comment]
Thank you It helped!
It may be necessary to add the message "You do not have permission to perform this action?"
